#!/bin/bash
separator="/"

#java MainFromZero < "./inputs/1_in.txt" > "./outputs/outputs1.txt"
#echo "DONE! 1"
#java Main < "./inputs/2_in.txt" > "./outputs/outputs2.txt"
#echo "DONE! 2"
#java Main < "./inputs/3_in.txt" > "./outputs/outputs3.txt"
#echo "DONE! 3"
#java Main < "./inputs/4_in.txt" > "./outputs/outputs4.txt"
#echo "DONE! 4"
#java Main < "./inputs/5_in.txt" > "./outputs/outputs5.txt"
#echo "DONE! 5"
#java Main < "./inputs/6_in.txt" > "./outputs/outputs6.txt"
#echo "DONE! 6"
java Main < "./inputs/7_in.txt" > "./outputs/outputs7.txt"
echo "DONE! 7"

echo "DONE!"
echo "DONE!"
echo "DONE!"
